version: '3.9'
services:
  mailer:
    image: sonalirajput/smtp-mailer:1
    depends_on:
      - mailhog
    ports:
      - "5000:5000"
    links:
      - "mailhog:mailhog"
    networks:
      - mail-network
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mail-network

networks:
  mail-network:
    
